create or replace TABLE CREDITGUARDIAN_AI.CORE.LOAN_HISTORY (
    LOAN_ID VARCHAR(15) NOT NULL,
    CUSTOMER_ID VARCHAR(10) NOT NULL,
    LOAN_TYPE VARCHAR(50) NOT NULL,
    SANCTIONED_AMOUNT NUMBER(18,2) NOT NULL,
    DISBURSED_AMOUNT NUMBER(18,2),
    OUTSTANDING_BALANCE NUMBER(18,2),
    INTEREST_RATE NUMBER(5,2),
    TENURE_MONTHS NUMBER(38,0),
    SANCTION_DATE DATE,
    MATURITY_DATE DATE,
    COLLATERAL_TYPE VARCHAR(100),
    COLLATERAL_VALUE NUMBER(18,2),
    LOAN_STATUS VARCHAR(30),
    PURPOSE VARCHAR(200),
    CURRENCY VARCHAR(3) DEFAULT 'USD',
    primary key (LOAN_ID),
    foreign key (CUSTOMER_ID) references CREDITGUARDIAN_AI.CORE.CUSTOMERS(CUSTOMER_ID)
) COMMENT = 'Loan facility history - sanctions, drawdowns, status';
