create or replace TABLE CREDITGUARDIAN_AI.CORE.LOAN_REPAYMENT (
    REPAYMENT_ID VARCHAR(20) NOT NULL,
    LOAN_ID VARCHAR(15) NOT NULL,
    CUSTOMER_ID VARCHAR(10) NOT NULL,
    DUE_DATE DATE NOT NULL,
    PAYMENT_DATE DATE,
    EMI_AMOUNT NUMBER(18,2),
    PRINCIPAL_COMPONENT NUMBER(18,2),
    INTEREST_COMPONENT NUMBER(18,2),
    PENALTY_AMOUNT NUMBER(18,2) DEFAULT 0,
    AMOUNT_PAID NUMBER(18,2),
    PAYMENT_STATUS VARCHAR(20),
    DAYS_OVERDUE NUMBER(38,0) DEFAULT 0,
    primary key (REPAYMENT_ID),
    foreign key (LOAN_ID) references CREDITGUARDIAN_AI.CORE.LOAN_HISTORY(LOAN_ID),
    foreign key (CUSTOMER_ID) references CREDITGUARDIAN_AI.CORE.CUSTOMERS(CUSTOMER_ID)
) COMMENT = 'Loan EMI repayment schedule and actuals';
