create or replace TABLE CREDITGUARDIAN_AI.CORE.BANK_TRANSACTIONS (
    TRANSACTION_ID VARCHAR(20) NOT NULL,
    CUSTOMER_ID VARCHAR(10) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(20),
    TRANSACTION_DATE DATE NOT NULL,
    TRANSACTION_TYPE VARCHAR(20) NOT NULL,
    DEBIT_AMOUNT NUMBER(18,2) DEFAULT 0,
    CREDIT_AMOUNT NUMBER(18,2) DEFAULT 0,
    RUNNING_BALANCE NUMBER(18,2),
    TRANSACTION_CATEGORY VARCHAR(50),
    DESCRIPTION VARCHAR(500),
    MONTH_YEAR VARCHAR(7),
    primary key (TRANSACTION_ID),
    foreign key (CUSTOMER_ID) references CREDITGUARDIAN_AI.CORE.CUSTOMERS(CUSTOMER_ID)
) COMMENT = 'Current account debit/credit transaction summary';
