create or replace TABLE CREDITGUARDIAN_AI.CORE.CREDIT_RATINGS (
    RATING_ID VARCHAR(20) NOT NULL,
    CUSTOMER_ID VARCHAR(10) NOT NULL,
    RATING_AGENCY VARCHAR(50) NOT NULL,
    RATING_TYPE VARCHAR(30),
    RATING VARCHAR(10) NOT NULL,
    RATING_OUTLOOK VARCHAR(20),
    RATING_DATE DATE NOT NULL,
    PREVIOUS_RATING VARCHAR(10),
    RATING_ACTION VARCHAR(20),
    VALID_UNTIL DATE,
    primary key (RATING_ID),
    foreign key (CUSTOMER_ID) references CREDITGUARDIAN_AI.CORE.CUSTOMERS(CUSTOMER_ID)
) COMMENT = 'External credit ratings from agencies (S&P, Moody, Fitch, local)';
