-- Raw JSON landing table
create or replace TABLE CREDITGUARDIAN_AI.CORE.MACRO_ECONOMIC_RAW (
    RAW_DATA VARIANT NOT NULL,
    SOURCE_FILE VARCHAR(500),
    LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Raw JSON landing table for macro-economic data feeds';

-- Structured indicators
create or replace TABLE CREDITGUARDIAN_AI.CORE.MACRO_ECONOMIC_INDICATORS (
    INDICATOR_ID VARCHAR(30) NOT NULL,
    INDICATOR_NAME VARCHAR(50) NOT NULL,
    INDICATOR_CATEGORY VARCHAR(30) NOT NULL,
    VALUE FLOAT NOT NULL,
    PREVIOUS_VALUE FLOAT,
    CHANGE_PCT FLOAT,
    UNIT VARCHAR(20),
    REPORT_DATE DATE NOT NULL,
    FREQUENCY VARCHAR(20),
    SOURCE VARCHAR(100),
    REGION VARCHAR(50) DEFAULT 'India',
    LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    constraint CHK_CATEGORY check (INDICATOR_CATEGORY IN ('INFLATION','RATES','CREDIT','COMMODITY','FX','GROWTH')),
    constraint PK_MACRO_INDICATORS primary key (INDICATOR_ID)
) COMMENT = 'Structured macro-economic indicators parsed from raw feed - CPI, rates, credit growth, FX, commodities';
