create or replace TABLE CREDITGUARDIAN_AI.CORE.REGULATORY_POLICIES (
    POLICY_ID VARCHAR(20) NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    ISSUING_AUTHORITY VARCHAR(100) NOT NULL,
    DOCUMENT_TYPE VARCHAR(50),
    SECTION VARCHAR(1000),
    CONTENT VARCHAR(16000) NOT NULL,
    EFFECTIVE_DATE DATE,
    REFERENCE_NUMBER VARCHAR(100),
    CATEGORY VARCHAR(50),
    RELEVANCE_TO_LENDING VARCHAR(200),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    constraint PK_REGULATORY_POLICIES primary key (POLICY_ID)
) COMMENT = 'Regulatory policy text for Cortex Search RAG - RBI, Basel, IRAC guidelines';
