create or replace TABLE CREDITGUARDIAN_AI.CORE.CREDIT_ASSESSMENTS (
    ASSESSMENT_ID VARCHAR(50) NOT NULL,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    ASSESSMENT_DATE DATE DEFAULT CURRENT_DATE(),
    RISK_SCORE FLOAT,
    RISK_GRADE VARCHAR(2),
    SMA_CATEGORY VARCHAR(10),
    AI_RECOMMENDATION VARCHAR(30),
    AI_NARRATIVE VARCHAR(16000),
    REGULATORY_CITATIONS VARCHAR(2000),
    CONFIDENCE_SCORE FLOAT,
    MODEL_USED VARCHAR(50),
    GENERATED_BY VARCHAR(100) DEFAULT CURRENT_USER(),
    GENERATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    constraint PK_CREDIT_ASSESSMENTS primary key (ASSESSMENT_ID)
) COMMENT = 'AI-generated credit assessment reports with regulatory citations - audit trail';
