create or replace TABLE CREDITGUARDIAN_AI.CORE.REGULATORY_DOCS_RAW (
    FILE_NAME VARCHAR(16777216),
    FILE_URL VARCHAR(16777216),
    PARSED_TEXT VARCHAR(16777216),
    LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    FILE_SIZE NUMBER(38,0) DEFAULT 0,
    FILE_HASH VARCHAR(64),
    PAGE_COUNT NUMBER(38,0) DEFAULT 0,
    PROCESSING_STATUS VARCHAR(20) DEFAULT 'PENDING',
    ERROR_MESSAGE VARCHAR(16777216),
    PROCESSED_AT TIMESTAMP_NTZ(9)
) COMMENT = 'Raw parsed text from PDFs with tracking metadata (hash, page count, status, errors)';
