create or replace TABLE CREDITGUARDIAN_AI.CORE.PDF_PROCESSING_LOG (
    RUN_ID VARCHAR(36) NOT NULL,
    RUN_STARTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    RUN_COMPLETED_AT TIMESTAMP_NTZ(9),
    FILES_DETECTED NUMBER(38,0) DEFAULT 0,
    FILES_NEW NUMBER(38,0) DEFAULT 0,
    FILES_PROCESSED NUMBER(38,0) DEFAULT 0,
    FILES_FAILED NUMBER(38,0) DEFAULT 0,
    POLICIES_LOADED NUMBER(38,0) DEFAULT 0,
    STATUS VARCHAR(20) DEFAULT 'RUNNING',
    ERROR_SUMMARY VARCHAR(16777216)
) COMMENT = 'Audit log for every PDF ingestion run (run_id, file counts, status, errors)';
